#define NO_AUTO_SHIFT_ALPHA 1

#undef TAPPING_TERM
#define TAPPING_TERM 170
#define LONG_TAPPING_TERM 300
#define TAPPING_TERM_PER_KEY
// #define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD

#define COMBO_COUNT 1
